### PR TITLE
Fix null Itemstacks in miner and recipes

### LINKED ISSUE #4321: [1.11.2] Digital Miner Bug
Hello,
when i have a Chest/Crate on the Digital Miner and choose Auto Pull.

`---- Minecraft Crash Report ----

WARNING: coremods are present:
  CreativePatchingLoader (CreativeCore v1.7.2 mc1.11.2.jar)
  LittlePatchingLoader (LittleTiles v1.4.7 mc1.11.2.jar)
  CCLCorePlugin (CodeChickenLib-1.11.2-2.6.0.254-universal.jar)
  DummyPlugin (ForgeEndertech-1.11.2-2.0.8.0-build.0025.jar)
  BCModPlugin (zz-backpacks 1.11.2 - 3.1.8.jar)
  ShetiPhian-ASM (shetiphiancore-1.11.0-3.4.4.jar)
  DynamicSurroundingsCore (DynamicSurroundings-1.11.2-3.3.3.1.jar)
Contact their authors BEFORE contacting forge

// You should try our sister game, Minceraft!

Time: 4/17/17 7:18 AM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at mekanism.common.tile.TileEntityDigitalMiner.setReplace(TileEntityDigitalMiner.java:384)
	at mekanism.common.tile.TileEntityDigitalMiner.onUpdate(TileEntityDigitalMiner.java:268)
	at mekanism.common.tile.TileEntityBasicBlock.func_73660_a(TileEntityBasicBlock.java:78)
	at net.minecraft.world.World.func_72939_s(World.java:1802)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:621)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:720)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at mekanism.common.tile.TileEntityDigitalMiner.setReplace(TileEntityDigitalMiner.java:384)
	at mekanism.common.tile.TileEntityDigitalMiner.onUpdate(TileEntityDigitalMiner.java:268)
	at mekanism.common.tile.TileEntityBasicBlock.func_73660_a(TileEntityBasicBlock.java:78)

-- Block entity being ticked --
Details:
	Name: minecraft:digitalminer // mekanism.common.tile.TileEntityDigitalMiner
	Block type: ID #2212 (tile.MachineBlock // null)
	Block data value: 4 / 0x4 / 0b0100
	Block location: World: (565,64,23), Chunk: (at 5,4,7 in 35,1; contains blocks 560,0,16 to 575,255,31), Region: (1,0; contains chunks 32,0 to 63,31, blocks 512,0,0 to 1023,255,511)
	Actual block type: ID #2212 (tile.MachineBlock // null)
	Actual block data value: 4 / 0x4 / 0b0100
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1802)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:621)

-- Affected level --
Details:
	Level name: Midgard
	All players: 1 total; [EntityPlayerMP['ChaosKaiBln'/141, l='Midgard', x=565.56, y=64.00, z=20.34]]
	Chunk stats: ServerChunkCache: 1363 Drop: 0
	Level seed: 250049605
	Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: true
	Level generator options: {"landScheme":"vanilla","tempScheme":"medium_zones","rainScheme":"medium_zones","biomeSize":"medium","amplitude":1.0,"generateBopOre":true,"generateBopSoils":true,"generateBopTrees":true,"generateBopGrasses":true,"generateBopFoliage":true,"generateBopFlowers":true,"generateBopPlants":true,"generateBopWaterPlants":true,"generateBopMushrooms":true,"generateRockFormations":true,"generatePoisonIvy":true,"generateFlax":true,"generateBerryBushes":true,"generateThorns":true,"generateQuicksand":true,"generateLiquidPoison":true,"generateHotSprings":true,"generateNetherHives":true,"generateNetherPlants":true,"generateEndFeatures":true,"mainNoiseScaleX":80.0,"mainNoiseScaleY":160.0,"mainNoiseScaleZ":80.0,"coordinateScale":684.412,"heightScale":684.412,"upperLimitScale":512.0,"lowerLimitScale":512.0}
	Level spawn location: World: (132,64,248), Chunk: (at 4,4,8 in 8,15; contains blocks 128,0,240 to 143,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 1642870 game time, 2474908 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 1417 (now: true), thunder time: 113453 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:720)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_101, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 718498496 bytes (685 MB) / 5610405888 bytes (5350 MB) up to 7635730432 bytes (7282 MB)
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms128M -Xmx8G -XX:MetaspaceSize=128M -XX:MaxMetaspaceSize=512M
	IntCache: cache: 0, tcache: 0, allocated: 5, tallocated: 104
	FML: MCP 9.38 Powered by Forge 13.20.0.2282 Optifine OptiFine_1.11.2_HD_U_B7 90 mods loaded, 90 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.0.2282.jar) 
	UCHIJAAAA	forge{13.20.0.2282} [Minecraft Forge] (forge-1.11.2-13.20.0.2282.jar) 
	UCHIJAAAA	creativecoredummy{1.0.0} [CreativeCoreDummy] (minecraft.jar) 
	UCHIJAAAA	littletilescore{1.0.0} [LittleTilesCore] (minecraft.jar) 
	UCHIJAAAA	backpacks16840{3.1.8} [Backpacks!] (zz-backpacks 1.11.2 - 3.1.8.jar) 
	UCHIJAAAA	ccl-entityhook{1.0} [ccl-entityhook] (CodeChickenLib-1.11.2-2.6.0.254-universal.jar) 
	UCHIJAAAA	actuallyadditions{1.11.2-r106} [Actually Additions] (ActuallyAdditions-1.11.2-r106.jar) 
	UCHIJAAAA	forgeendertech{1.11.2-2.0.8.0} [Forge Endertech] (ForgeEndertech-1.11.2-2.0.8.0-build.0025.jar) 
	UCHIJAAAA	adchimneys{1.11.2-2.0.8.0} [Advanced Chimneys] (AdChimneys-1.11.2-2.0.8.0-build.0027.jar) 
	UCHIJAAAA	jei{4.2.10.248} [Just Enough Items] (jei_1.11.2-4.2.10.248.jar) 
	UCHIJAAAA	appleskin{1.0.6} [AppleSkin] (AppleSkin-mc1.11-1.0.6.jar) 
	UCHIJAAAA	immcraft{1.3.1} [Immersive Craft] (immcraft-1.1x-1.3.1.jar) 
	UCHIJAAAA	aquamunda{0.1.1beta} [Aqua Munda] (aquamunda-0.1.1beta.jar) 
	UCHIJAAAA	bdlib{1.13.2.7} [BD Lib] (bdlib-1.13.2.7-mc1.11.2.jar) 
	UCHIJAAAA	mekanism{9.3.0} [Mekanism] (Mekanism-1.11.2-9.3.0.homebaked.jar) 
	UCHIJAAAA	betterwithmods{1.1.5} [Better With Mods] (Better With Mods-1.1.5-1.11.2.jar) 
	UCHIJAAAA	biomesoplenty{6.0.2.2168} [Biomes O' Plenty] (BiomesOPlenty-1.11.2-6.0.2.2168-universal.jar) 
	UCHIJAAAA	buildcraftlib{7.99.0} [BuildCraft Lib] (buildcraft-7.99.0.jar) 
	UCHIJAAAA	buildcraftcore{7.99.0} [BuildCraft] (buildcraft-7.99.0.jar) 
	UCHIJAAAA	buildcraftfactory{7.99.0} [BC Factory] (buildcraft-7.99.0.jar) 
	UCHIJAAAA	buildcrafttransport{7.99.0} [BC Transport] (buildcraft-7.99.0.jar) 
	UCHIJAAAA	buildcraftbuilders{7.99.0} [BC Builders] (buildcraft-7.99.0.jar) 
	UCHIJAAAA	buildcraftenergy{7.99.0} [BC Energy] (buildcraft-7.99.0.jar) 
	UCHIJAAAA	buildcraftrobotics{7.99.0} [BC Robotics] (buildcraft-7.99.0.jar) 
	UCHIJAAAA	buildcraftsilicon{7.99.0} [BC Silicon] (buildcraft-7.99.0.jar) 
	UCHIJAAAA	cfm{4.1.2} [MrCrayfish's Furniture Mod] (cfm-4.1.2-mc1.11.2.jar) 
	UCHIJAAAA	chameleon{1.11-3.0.2} [Chameleon] (Chameleon-1.11-3.0.2.jar) 
	UCHIJAAAA	charcoal_pit{1.2_1} [Charcoal Pit] (CharcoalPit-[1.11.2]-1.2_1.jar) 
	UCHIJAAAA	codechickenlib{2.6.0.254} [CodeChicken Lib] (CodeChickenLib-1.11.2-2.6.0.254-universal.jar) 
	UCHIJAAAA	chickenchunks{2.3.0.63} [ChickenChunks] (ChickenChunks-1.11.2-2.3.0.63-universal.jar) 
	UCHIJAAAA	cookingforblockheads{5.3.20} [Cooking for Blockheads] (CookingForBlockheads_1.11.2-5.3.20.jar) 
	UCHIJAAAA	xaerocraftwp{1.3.1} [Craftable Waypoints] (Craftable_Waypoints_1.3.1_Forge_1.11.2.jar) 
	UCHIJAAAA	crafttweakerjei{1.0.1} [CraftTweaker JEI Support] (CraftTweaker-1.11.2-3.0.24.jar) 
	UCHIJAAAA	crafttweaker{3.0.24} [Crafttweaker] (CraftTweaker-1.11.2-3.0.24.jar) 
	UCHIJAAAA	ctgui{1.0.0} [CT-GUI] (CraftTweaker-1.11.2-3.0.24.jar) 
	UCHIJAAAA	creativecore{1.5.0} [CreativeCore] (CreativeCore v1.7.2 mc1.11.2.jar) 
	UCHIJAAAA	koresample{1.11.2-L1} [Kore Sample] (koresample-1.11.2.jar) 
	UCHIJAAAA	dendrology{1.11.2-L1.0.1} [Ancient Trees] (dendrology-1.11.2-L1.0.1.jar) 
	UCHIJAAAA	dsurround{3.3.3.1} [Dynamic Surroundings] (DynamicSurroundings-1.11.2-3.3.3.1.jar) 
	UCHIJAAAA	enderstorage{1.0} [EnderStorage] (EnderStorage-1.11.2-2.3.0.112-universal.jar) 
	UCHIJAAAA	extrautils2{1.0} [extrautils2] (extrautils2-1.11.2-1.3.3.jar) 
	UCHIJAAAA	fastleafdecay{v12} [Fast Leaf Decay] (FastLeafDecay-v12.jar) 
	UCHIJAAAA	forestry{5.3.3.91} [Forestry] (forestry_1.11.2-5.3.3.91.jar) 
	UCHIJAAAA	fp{25.1.15 pre} [Futurepack] (Futurepack-1.11.2-25.1.15.jar) 
	UCHIJAAAA	fp.api{1.1.0} [Futurepack API] (Futurepack-1.11.2-25.1.15.jar) 
	UCHIJAAAA	pressure{1.3.1.5} [Pressure Pipes] (pressure-1.3.1.5-mc1.11.2.jar) 
	UCHIJAAAA	advgenerators{0.9.20.5} [Advanced Generators] (generators-0.9.20.5-mc1.11.2.jar) 
	UCHIJAAAA	gravestone{1.7.2} [Gravestone] (GraveStone Mod 1.7.2.jar) 
	UCHIJAAAA	hardcoreore{0.0.16} [Hardcore ORE] (HardcoreORE-1.11.2-0.0.16.jar) 
	UCHIJAAAA	harvest{1.11-1.2.0-12} [Harvest] (Harvest-1.11-1.2.0-12.jar) 
	UCHIJAAAA	hopperducts{1.4.9} [Hopper Ducts] (hopperducts-mc1.11.2-1.4.9.jar) 
	UCHIJAAAA	infinitefluids{1.1.0} [InfiniteFluids] (infinitefluids-1.11-1.1.0.jar) 
	UCHIJAAAA	ironchest{1.11.2-7.0.18.800} [Iron Chest] (ironchest-1.11.2-7.0.18.800.jar) 
	UCHIJAAAA	littletiles{1.3.0} [LittleTiles] (LittleTiles v1.4.7 mc1.11.2.jar) 
	UCHIJAAAA	llor{1.1.3-mc1.11.2} [Light Level Overlay Reloaded] (LLOverlayReloaded-1.1.3-mc1.11.2.jar) 
	UCHIJAAAA	lumberjack{1.0} [lumberjack] (Lumberjack-1.11.2-1.3.1.48.jar) 
	UCHIJAAAA	mekanismgenerators{9.3.0} [MekanismGenerators] (MekanismGenerators-1.11.2-9.3.0.homebaked.jar) 
	UCHIJAAAA	mekanismtools{9.3.0} [MekanismTools] (MekanismTools-1.11.2-9.3.0.homebaked.jar) 
	UCHIJAAAA	mineclock{1.0} [MineClock] (mineclock-1.0.2.jar) 
	UCHIJAAAA	mtrm{1.2.1.23} [MineTweakerRecipeMaker] (MineTweakerRecipeMaker-1.11.2-1.2.1.23.jar) 
	UCHIJAAAA	modnametooltip{1.7.0} [Mod Name Tooltip] (modnametooltip_1.11-1.7.0.jar) 
	UCHIJAAAA	shetiphiancore{3.4.4} [ShetiPhian-Core] (shetiphiancore-1.11.0-3.4.4.jar) 
	UCHIJAAAA	multibeds{1.3.3} [Multi-Beds] (multibeds-1.11.0-1.3.3.jar) 
	UCHIJAAAA	recipehandler{0.7} [NoMoreRecipeConflict] (NoMoreRecipeConflict-0.7(1.11).jar) 
	UCHIJAAAA	rftools{5.91} [RFTools] (rftools-1.1x-5.91.jar) 
	UCHIJAAAA	rftoolsdim{4.55} [RFTools Dimensions] (rftoolsdim-1.1x-4.55.jar) 
	UCHIJAAAA	persistentbits{1.0.6} [Persistent Bits] (PersistentBits-1.11-1.0.6.jar) 
	UCHIJAAAA	jp.crafterkina.pipes{1.1.0.12} [Pipes] (Pipes-1.11-1.1.0.12.jar) 
	UCHIJAAAA	platforms{1.3.4} [Platforms] (platforms-1.11.0-1.3.4.jar) 
	UCHIJAAAA	primal{0.3.14} [PrimalCore] (PrimalCore-0.3.14.jar) 
	UCHIJAAAA	rangedpumps{0.4} [Ranged Pumps] (rangedpumps-0.4.jar) 
	UCHIJAAAA	refinedstorage{1.4.2} [Refined Storage] (refinedstorage-1.4.2.jar) 
	UCHIJAAAA	rftoolscontrol{1.6.6} [RFTools Control] (rftoolsctrl-1.1x-1.6.6.jar) 
	UCHIJAAAA	silentlib{2.1.0} [Silent Lib] (SilentLib-1.11.x-2.1.0-53.jar) 
	UCHIJAAAA	silentgems{2.3.7} [Silent's Gems] (SilentsGems-1.11.x-2.3.7-161.jar) 
	UCHIJAAAA	sgextraparts{1.2.5} [Silent's Gems: Extra Parts] (SGExtraParts-1.11.x-1.2.5-20.jar) 
	UCHIJAAAA	soundfilters{0.9_for_1.9} [Sound Filters] (SoundFilters-0.9_for_1.11.jar) 
	UCHIJAAAA	storagedrawers{1.11.2-4.2.1} [Storage Drawers] (StorageDrawers-1.11.2-4.2.1.jar) 
	UCHIJAAAA	substratum{1.9.2.0} [Substratum] (Substratum-1.11.2-1.9.2.0.jar) 
	UCHIJAAAA	theoneprobe{1.4.6} [The One Probe] (theoneprobe-1.1x-1.4.6.jar) 
	UCHIJAAAA	thutcore{4.4.1} [ThutCore] (thutcore-4.4.1.jar) 
	UCHIJAAAA	thuttech{5.0.0} [Thut's Tech] (thuttech-5.0.0.jar) 
	UCHIJAAAA	torohealthmod{1.11.2-11} [ToroHealth Damage Indicators] (torohealth-1.11.2-11.jar) 
	UCHIJAAAA	toroquest{1.11.2-3.4} [ToroQuest] (toroquest-1.11.2-3.4.jar) 
	UCHIJAAAA	translocator{2.2.0.59} [Translocator] (Translocators-1.11.2-2.2.0.59-universal.jar) 
	UCHIJAAAA	universalwrench{1.0.7} [Thiakil's Universal Wrench] (universalwrench-1.11.2-1.0.7-d6eb4c2.jar) 
	UCHIJAAAA	xaerominimap{1.12.6} [Xaero's Minimap] (Xaeros_Minimap_FP1.12.6_Forge_1.11.jar) 
	UCHIJAAAA	xaeroworldmap{1.8.1} [Xaero's World Map] (XaerosWorldMap_b1.8.1_Forge_1.11.jar) 
	Loaded coremods (and transformers): 
CreativePatchingLoader (CreativeCore v1.7.2 mc1.11.2.jar)
  
LittlePatchingLoader (LittleTiles v1.4.7 mc1.11.2.jar)
  com.creativemd.littletiles.LittleTilesTransformer
CCLCorePlugin (CodeChickenLib-1.11.2-2.6.0.254-universal.jar)
  codechicken.lib.asm.ClassHierarchyManager
  codechicken.lib.asm.CCL_ASMTransformer
DummyPlugin (ForgeEndertech-1.11.2-2.0.8.0-build.0025.jar)
  
BCModPlugin (zz-backpacks 1.11.2 - 3.1.8.jar)
  brad16840.common.asm.ClassTransformer
ShetiPhian-ASM (shetiphiancore-1.11.0-3.4.4.jar)
  shetiphian.core.asm.ClassTransformer
DynamicSurroundingsCore (DynamicSurroundings-1.11.2-3.3.3.1.jar)
  org.blockartistry.mod.DynSurround.asm.Transformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	List of loaded APIs: 
		* actuallyadditionsapi (33) from ActuallyAdditions-1.11.2-r106.jar
		* BetterWithModsAPI (Beta 0.6) from Better With Mods-1.1.5-1.11.2.jar
		* BuildCraftAPI|blocks (1.0) from buildcraft-7.99.0.jar
		* BuildCraftAPI|blueprints (1.5) from buildcraft-7.99.0.jar
		* BuildCraftAPI|boards (2.0) from buildcraft-7.99.0.jar
		* BuildCraftAPI|core (2.2) from buildcraft-7.99.0.jar
		* BuildCraftAPI|crops (1.1) from buildcraft-7.99.0.jar
		* BuildCraftAPI|enums (1.0) from buildcraft-7.99.0.jar
		* BuildCraftAPI|events (2.0) from buildcraft-7.99.0.jar
		* BuildCraftAPI|facades (1.1) from buildcraft-7.99.0.jar
		* BuildCraftAPI|filler (4.0) from buildcraft-7.99.0.jar
		* BuildCraftAPI|fuels (2.0) from buildcraft-7.99.0.jar
		* BuildCraftAPI|gates (4.1) from buildcraft-7.99.0.jar
		* BuildCraftAPI|items (1.1) from buildcraft-7.99.0.jar
		* BuildCraftAPI|library (2.0) from buildcraft-7.99.0.jar
		* BuildCraftAPI|lists (1.0) from buildcraft-7.99.0.jar
		* BuildCraftAPI|power (1.3) from buildcraft-7.99.0.jar
		* BuildCraftAPI|recipes (3.0) from buildcraft-7.99.0.jar
		* BuildCraftAPI|robotics (3.0) from buildcraft-7.99.0.jar
		* BuildCraftAPI|statements (1.1) from buildcraft-7.99.0.jar
		* BuildCraftAPI|tablet (1.0) from buildcraft-7.99.0.jar
		* BuildCraftAPI|tiles (1.2) from buildcraft-7.99.0.jar
		* BuildCraftAPI|tools (1.0) from buildcraft-7.99.0.jar
		* BuildCraftAPI|transport (5.0) from buildcraft-7.99.0.jar
		* CoFHAPI (1.8.9R1.2.0B1) from Futurepack-1.11.2-25.1.15.jar
		* cofhapi (1.4.0) from extrautils2-1.11.2-1.3.3.jar
		* CoFHAPI|energy (1.8.9R1.2.0B1) from mcjtylib-1.1x-2.3.11.jar
		* cofhapi|energy (1.4.0) from extrautils2-1.11.2-1.3.3.jar
		* CoFHAPI|item (1.8.9R1.2.0B1) from Mekanism-1.11.2-9.3.0.homebaked.jar
		* compatlayer (0.2.5) from compatlayer-1.11.2-0.2.5.jar
		* dsurroundAPI (1.0) from DynamicSurroundings-1.11.2-3.3.3.1.jar
		* ForestryAPI|apiculture (5.0.0) from forestry_1.11.2-5.3.3.91.jar
		* ForestryAPI|arboriculture (4.2.1) from forestry_1.11.2-5.3.3.91.jar
		* ForestryAPI|circuits (3.1.0) from forestry_1.11.2-5.3.3.91.jar
		* ForestryAPI|climate (2.1.0) from forestry_1.11.2-5.3.3.91.jar
		* ForestryAPI|core (5.1.0) from forestry_1.11.2-5.3.3.91.jar
		* ForestryAPI|farming (2.2.0) from forestry_1.11.2-5.3.3.91.jar
		* ForestryAPI|food (1.1.0) from forestry_1.11.2-5.3.3.91.jar
		* ForestryAPI|fuels (3.0.0) from forestry_1.11.2-5.3.3.91.jar
		* ForestryAPI|genetics (4.7.1) from forestry_1.11.2-5.3.3.91.jar
		* ForestryAPI|greenhouse (5.2.0) from forestry_1.11.2-5.3.3.91.jar
		* ForestryAPI|hives (4.1.0) from forestry_1.11.2-5.3.3.91.jar
		* ForestryAPI|lepidopterology (1.4.0) from forestry_1.11.2-5.3.3.91.jar
		* ForestryAPI|mail (3.1.0) from forestry_1.11.2-5.3.3.91.jar
		* ForestryAPI|multiblock (3.0.0) from forestry_1.11.2-5.3.3.91.jar
		* ForestryAPI|recipes (5.4.0) from forestry_1.11.2-5.3.3.91.jar
		* ForestryAPI|storage (5.0.0) from forestry_1.11.2-5.3.3.91.jar
		* ForestryAPI|world (2.1.0) from forestry_1.11.2-5.3.3.91.jar
		* jp.crafterkina.pipes.api (1.0) from Pipes-1.11-1.1.0.12.jar
		* jp.crafterkina.pipes.api.pipe (1.0) from Pipes-1.11-1.1.0.12.jar
		* jp.crafterkina.pipes.api.render (1.0) from Pipes-1.11-1.1.0.12.jar
		* JustEnoughItemsAPI (4.11.0) from jei_1.11.2-4.2.10.248.jar
		* mcjtylib_ng (2.3.11) from mcjtylib-1.1x-2.3.11.jar
		* MekanismAPI|core (9.0.0) from Mekanism-1.11.2-9.3.0.homebaked.jar
		* MekanismAPI|energy (9.0.0) from Mekanism-1.11.2-9.3.0.homebaked.jar
		* MekanismAPI|gas (9.0.0) from Mekanism-1.11.2-9.3.0.homebaked.jar
		* MekanismAPI|infuse (9.0.0) from Mekanism-1.11.2-9.3.0.homebaked.jar
		* MekanismAPI|laser (9.0.0) from Mekanism-1.11.2-9.3.0.homebaked.jar
		* MekanismAPI|transmitter (9.0.0) from Mekanism-1.11.2-9.3.0.homebaked.jar
		* MekanismAPI|util (9.0.0) from Mekanism-1.11.2-9.3.0.homebaked.jar
		* pressureAPI (1.3.1.5) from pressure-1.3.1.5-mc1.11.2.jar
		* SilentGemsAPI (2) from SilentsGems-1.11.x-2.3.7-161.jar
		* StorageDrawersAPI (1.10.2-1.3.0) from StorageDrawers-1.11.2-4.2.1.jar
		* StorageDrawersAPI|config (1.7.10-1.2.0) from refinedstorage-1.4.2.jar
		* StorageDrawersAPI|event (1.10.2-1.3.0) from StorageDrawers-1.11.2-4.2.1.jar
		* StorageDrawersAPI|pack (1.7.10-1.2.0) from refinedstorage-1.4.2.jar
		* StorageDrawersAPI|registry (1.7.10-1.2.0) from refinedstorage-1.4.2.jar
		* StorageDrawersAPI|render (1.7.10-1.2.0) from refinedstorage-1.4.2.jar
		* StorageDrawersAPI|storage (1.10.2-1.3.0) from StorageDrawers-1.11.2-4.2.1.jar
		* StorageDrawersAPI|storage-attribute (1.10.2-1.3.0) from StorageDrawers-1.11.2-4.2.1.jar
		* theoneprobe_api (1.4.4) from theoneprobe-1.1x-1.4.6.jar
		* thut|API (1.0.0) from thutcore-4.4.1.jar
		* universalwrenchAPI (1.0) from universalwrench-1.11.2-1.0.7-d6eb4c2.jar
		* universalwrenchAPI|capabilities (1.0) from universalwrench-1.11.2-1.0.7-d6eb4c2.jar
	chickenchunks Invalid Fingerprint Reports: - No invalid fingerprints.: 
	enderstorage Invalid Fingerprint Reports: - No invalid fingerprints.: 
	translocator Invalid Fingerprint Reports: - No invalid fingerprints.: 
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['ChaosKaiBln'/141, l='Midgard', x=565.56, y=64.00, z=20.34]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'`

### PR DESCRIPTION
**Pull request by thommy101**
Fixes #4321 and #4319
Thanks to @allanf181 for finding the recipe bug

### CODE REVIEW

File: src/main/java/mekanism/client/gui/GuiDictionary.java [hunk 1]
```diff
@@ -23,7 +23,7 @@
 @SideOnly(Side.CLIENT)
 public class GuiDictionary extends GuiMekanism
 {
-	public ItemStack itemType;
+	public ItemStack itemType = ItemStack.EMPTY;
```
Comment (thommy101) [inline src/main/java/mekanism/client/gui/GuiDictionary.java]: Found a bug while testing, shift right click to open the Dictionaries GUI resulted in a NPE.

**Comment by Ristovski** [comment]
@thommy101 Honestly man, good job. I've been experiencing issues related to this for couple of days now. Keep up the great work.

**Comment by aidancbrady** [comment]
Awesome, thanks
